services:
  - type: web
    name: cineapi
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: PORT
        value: 8000
      - key: MASTER_API_KEY
        generateValue: true
      - key: CLOUDFLARE_API_TOKEN
        sync: false
      - key: CLOUDFLARE_ZONE_ID
        sync: false
      - key: DOWNLOAD_DIR
        value: /tmp/cineapi_downloads
      - key: DOWNLOAD_TTL_HOURS
        value: 2
      - key: MAX_CONCURRENT_DOWNLOADS
        value: 3
    healthCheckPath: /health
    autoDeploy: true